title: Will Webberley 
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 5
paginate_path: "/blog/page/:num/"
permalink: pretty
exclude: [package.json, Gemfile, Gemfile.lock, _config.yml]

collections:
  - publications

markdown: kramdown
gems: [jekyll-paginate]
