title: Will Webberley 
baseurl: "" # the subpath of your site, e.g. /blog
paginate: 5
paginate_path: "/blog/page:num/"
exclude: [build.tar.gz, deploy, package.json]

collections:
  - publications

markdown: kramdown
gems: [jekyll-paginate]
